spring.application.name=Proyecto1Progra4
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bolsaempleo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:WmViQGJvbHNhRW1wbGVvU2VjcmV0S2V5VG9rZW5Qcm95ZWN0bzIwMjY=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.web.resources.static-locations=classpath:/static/
